#docker-compose up
version: "3.9"
services:
  postgres:
    container_name: YTBotDB
    image: postgres
    environment:
      POSTGRES_DB: "YTBotDB"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345"
    ports:
      - "5432:5432"